"""deleted test

Revision ID: 0c39d54aa1c1
Revises: 824d860f5198
Create Date: 2019-07-16 15:17:34.960977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c39d54aa1c1'
down_revision = '824d860f5198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('underlying', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('symbolId', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='testing_pkey')
    )
    # ### end Alembic commands ###
