"""pricing changes

Revision ID: 20e373ff406d
Revises: 0c39d54aa1c1
Create Date: 2019-07-22 12:07:48.645510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e373ff406d'
down_revision = '0c39d54aa1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('askMarket', sa.Float(), nullable=True))
    op.add_column('pricing', sa.Column('bidMarket', sa.Float(), nullable=True))
    op.add_column('pricing', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing', 'comment')
    op.drop_column('pricing', 'bidMarket')
    op.drop_column('pricing', 'askMarket')
    # ### end Alembic commands ###
