"""plswork

Revision ID: 388aba519988
Revises: 6030a0e50b7f
Create Date: 2019-08-01 21:01:29.956719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388aba519988'
down_revision = '6030a0e50b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
