"""d1

Revision ID: 446177981ee3
Revises: 388aba519988
Create Date: 2019-08-01 21:46:41.814952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446177981ee3'
down_revision = '388aba519988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leg',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_leg_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instruction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='leg_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leg_pkey')
    )
    # ### end Alembic commands ###
