"""create second

Revision ID: 6dda1a51beac
Revises: c2aa870be645
Create Date: 2019-07-31 16:25:38.275299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dda1a51beac'
down_revision = 'c2aa870be645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
