"""aaa

Revision ID: 7edd024a2eb6
Revises: 4d2f0a01de8d
Create Date: 2019-08-12 16:29:22.712460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edd024a2eb6'
down_revision = '4d2f0a01de8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing', sa.Column('strikes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing', 'strikes')
    # ### end Alembic commands ###
