"""new iv fields

Revision ID: f6ec4e714f81
Revises: 44ee49b20f4b
Create Date: 2019-08-12 10:25:26.443253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ec4e714f81'
down_revision = '44ee49b20f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.Float(), nullable=True),
    sa.Column('symbolId', sa.String(length=25), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('bidPrice', sa.Float(), nullable=True),
    sa.Column('bidSize', sa.Float(), nullable=True),
    sa.Column('bidMarket', sa.Float(), nullable=True),
    sa.Column('askPrice', sa.Float(), nullable=True),
    sa.Column('askSize', sa.Float(), nullable=True),
    sa.Column('askMarket', sa.Float(), nullable=True),
    sa.Column('ivAtBid', sa.Float(), nullable=True),
    sa.Column('ivAtAsk', sa.Float(), nullable=True),
    sa.Column('ivBidMarket', sa.String(), nullable=True),
    sa.Column('ivAskMarket', sa.String(), nullable=True),
    sa.Column('ivBidFit', sa.String(), nullable=True),
    sa.Column('ivAskFit', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing')
    # ### end Alembic commands ###
