"""created pricing

Revision ID: f9e210eaf3f1
Revises: 8128cf96f544
Create Date: 2019-07-22 12:11:34.621289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e210eaf3f1'
down_revision = '8128cf96f544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.Float(), nullable=True),
    sa.Column('symbolId', sa.String(length=25), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('bidPrice', sa.Float(), nullable=True),
    sa.Column('bidSize', sa.Float(), nullable=True),
    sa.Column('bidMarket', sa.Float(), nullable=True),
    sa.Column('askPrice', sa.Float(), nullable=True),
    sa.Column('askSize', sa.Float(), nullable=True),
    sa.Column('askMarket', sa.Float(), nullable=True),
    sa.Column('ivAtBid', sa.Float(), nullable=True),
    sa.Column('ivAtAsk', sa.Float(), nullable=True),
    sa.Column('ivBidFit', sa.String(), nullable=True),
    sa.Column('ivAskFit', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing')
    # ### end Alembic commands ###
