"""rip

Revision ID: fcaf60be842c
Revises: 4a1f7366cfd6
Create Date: 2019-08-02 00:07:19.078103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcaf60be842c'
down_revision = '4a1f7366cfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
